// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oijpklutvrskpueeavde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9panBrbHV0dnJza3B1ZWVhdmRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNDQ4OTcsImV4cCI6MjA2MDcyMDg5N30._zGkcoHrnH9FAhtltZyk23u3XMlW1zuBTrRqt9pxvXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);